---
version: '3.5'
services:

  # in order to run kafka-producer-perf-test
  tools:
    image: cnfltraining/training-tools:5.4
    hostname: tools
    container_name: tools
    volumes:
      - ~/.ccloud/config:/tmp/config
    entrypoint: /bin/bash
    tty: true

  ccloud_exporter:
    image: dabz/ccloudexporter:latest
    hostname: ccloud_exporter
    container_name: ccloud_exporter
    environment:
      CCLOUD_USER: ${API_KEY_CLOUD}
      CCLOUD_PASSWORD: ${API_SECRET_CLOUD}
    command: -config /conf/config.yml
    volumes:
        - ./config.yml:/conf/config.yml

  prometheus:
    image: prom/prometheus
    hostname: prometheus
    container_name: prometheus
    ports:
      - 9090:9090
    restart: always
    volumes:
      - ./prometheus/:/etc/prometheus/
    depends_on:
      - ccloud_exporter

  grafana:
    image: grafana/grafana:7.0.6
    hostname: grafana
    container_name: grafana
    environment:
      GF_INSTALL_PLUGINS: grafana-piechart-panel
    ports:
      - 3000:3000
    volumes:
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    depends_on:
      - prometheus