---
version: '3.5'
services:

  sfdx-cli:
    image: vdesabou/sfdx-cli:latest # forked from salestrip/sfdx-cli to add plugin sfpowerkit
    hostname: sfdx-cli
    container_name: sfdx-cli
    command: "sleep infinity"

  connect:
    volumes:
    # FIXTHIS
    - ../../connect/connect-salesforce-pushtopics-source/kafka-connect-salesforce-common-1.6.1-SNAPSHOT.jar:/usr/share/confluent-hub-components/confluentinc-kafka-connect-salesforce/lib/kafka-connect-salesforce-common-1.6.0.jar
    - ../../connect/connect-salesforce-pushtopics-source/kafka-connect-salesforce-push-topic-1.6.1-SNAPSHOT.jar:/usr/share/confluent-hub-components/confluentinc-kafka-connect-salesforce/lib/kafka-connect-salesforce-push-topic-1.6.0.jar
    - ../../connect/connect-salesforce-pushtopics-source/kafka-connect-salesforce-sobject-1.6.1-SNAPSHOT.jar:/usr/share/confluent-hub-components/confluentinc-kafka-connect-salesforce/lib/kafka-connect-salesforce-sobject-1.6.0.jar
    environment:
      CONNECT_PLUGIN_PATH: /usr/share/confluent-hub-components/confluentinc-kafka-connect-salesforce